-- category_regulations seed — banned + restricted entries across 10
-- regulated subcategories × 20 supported countries.
--
-- We only seed bans + meaningful restrictions. Absence of a row is
-- interpreted by the runner as "no special restriction" (default
-- allowed). This keeps the table focused on actionable data.
--
-- Sources: each row cites the specific Act / regulation / agency.
-- The runner exposes these directly in the result page warnings so
-- a customer's legal team can verify the basis for any exclusion.

insert into public.category_regulations
  (regulated_category, country_code, status, reason, source, source_url, effective_year)
values

-- ──────────────────────────────────────────────────────────────────
-- VAPING (e-cigarettes / vape pods)
-- ──────────────────────────────────────────────────────────────────
('vaping', 'SG', 'banned',
 '전자담배 및 모조 담배 제품의 수입·판매·소지가 모두 불법입니다.',
 'Tobacco (Control of Advertisements and Sale) Act (Cap. 309); HSA',
 'https://www.hsa.gov.sg', 2018),
('vaping', 'TH', 'banned',
 '전자담배의 수입·판매·소지가 모두 금지됩니다.',
 'Customs Act + Tobacco Products Control Act',
 'https://www.customs.go.th', 2014),
('vaping', 'IN', 'banned',
 '전자담배 및 유사 기기의 생산·제조·수입·수출·운송·판매·유통·보관·광고가 전면 금지됩니다.',
 'Prohibition of Electronic Cigarettes Act 2019 (PECA)',
 'https://www.indiacode.nic.in', 2019),
('vaping', 'BR', 'banned',
 '전자담배의 수입·판매·광고가 전면 금지되며, 2023년 ANVISA 결의로 재확인되었습니다.',
 'ANVISA RDC No. 46/2009; ANVISA 재확인 결의 (2023)',
 'https://www.gov.br/anvisa', 2009),
('vaping', 'VN', 'banned',
 '전자담배 및 가열담배 제품의 수입·판매·유통이 전면 금지됩니다.',
 '베트남 정부 결의 제115/2020/QH14호 및 보건부 지침 (2024)',
 null, 2024),
('vaping', 'MX', 'banned',
 '대통령령으로 전자담배·니코틴 함유 베이프 제품의 수입·판매가 금지됩니다.',
 'Decreto Presidencial 31/2022',
 null, 2022),
('vaping', 'CN', 'restricted',
 '전자담배는 국가담배전매국(STMA)의 허가가 필요하며 외국 기업의 시장 진입 장벽이 매우 높습니다.',
 '电子烟管理办法 (2022, 国家烟草专卖局)',
 null, 2022),
('vaping', 'KR', 'restricted',
 '니코틴이 없는 금연 보조 베이프라도 전자담배 형태의 제품은 국민건강증진법 및 담배사업법의 규제 대상이 될 수 있으며, 의약외품 또는 의료기기로 분류될 경우 식약처의 별도 허가가 필요합니다.',
 '국민건강증진법, 담배사업법, 의약품 등의 안전에 관한 규칙 (식품의약품안전처)',
 null, null),
('vaping', 'JP', 'restricted',
 '니코틴 미함유 전자담배는 담배사업법상 ''담배''로 분류되지 않으나, 금연 보조 효능을 표방하는 경우 의약품·의료기기 등의 품질, 유효성 및 안전성의 확보 등에 관한 법률 (PMD Act)에 따라 의약품 또는 의료기기로 허가를 받아야 할 수 있습니다.',
 '医薬品、医療機器等の品質、有効性及び安全性の確保等に関する法律 (PMD Act, 2014)',
 null, 2014),
('vaping', 'US', 'restricted',
 'FDA의 담배 제품 규제(PMTA) 대상에서 제외될 수 있으나, 금연 보조 효능을 표방할 경우 FDA의 의약품 또는 의료기기 허가가 필요합니다. 또한 주(州)별로 전자담배 유사 제품에 대한 별도 규제가 존재하며, 일부 주에서는 니코틴 미함유 제품도 전자담배로 분류하여 규제합니다.',
 'Federal Food, Drug, and Cosmetic Act (FD&C Act); Family Smoking Prevention and Tobacco Control Act (2009); FDA Deeming Rule (2016)',
 null, 2016),
('vaping', 'GB', 'restricted',
 '전자담배는 담배 및 관련 제품 규정(TRPR)의 직접 규제 대상은 아니나, 금연 보조 효능을 표방하는 경우 MHRA(의약품 및 의료제품 규제청)의 의약품 허가가 필요합니다. 또한 일회용 전자담배는 2024년부터 환경 규제(일회용 플라스틱 규제)의 강화로 추가적인 제약이 있습니다.',
 'Tobacco and Related Products Regulations 2016 (SI 2016/507); Medicines Act 1968',
 null, 2024),
('vaping', 'AE', 'restricted',
 '전자담배는 2019년 말부터 합법화되었으나 ESMA / 보건부 등록 및 표준 인증이 필수.',
 'ESMA UAE.S 5030:2019',
 null, 2019),
('vaping', 'SA', 'restricted',
 'SFDA 등록 + Halal-적합성 검증 필요. 광고는 사실상 금지.',
 'SFDA Vaping Products Regulation',
 'https://www.sfda.gov.sa', 2020),
('vaping', 'AU', 'restricted',
 '니코틴 함유 vape는 2024년 처방전 의무화 (의사 처방 없이 구매 불가).',
 'Therapeutic Goods (Vaping Reforms) Act 2024',
 null, 2024),
('vaping', 'TW', 'banned',
 '전자담배(가향·니코틴 포함 일체) 및 가열담배의 제조·수입·판매·광고가 전면 금지.',
 '菸害防制法 修正案 (2023)',
 null, 2023),
('vaping', 'MY', 'restricted',
 '니코틴 함유 vape 는 2023년 의약품 분류에서 제외, 일반 판매 가능하나 18세 미만 판매 금지.',
 'Control of Tobacco Product and Smoking Bill 2023',
 null, 2023),

-- ──────────────────────────────────────────────────────────────────
-- ALCOHOL
-- ──────────────────────────────────────────────────────────────────
('alcohol', 'SA', 'banned',
 '주류의 생산·수입·판매·소비가 전면 금지됩니다 (이슬람 율법).',
 'Saudi Arabia Anti-Drug Law',
 null, null),
('alcohol', 'AE', 'restricted',
 '비무슬림에 한해 면허 매장에서만 구매 가능. 두바이는 2023년 면허 의무 폐지하였으나 이외 emirate는 면허 필요.',
 'UAE Federal Law on Combating Narcotics; Emirate-level licensing',
 null, 2023),
('alcohol', 'ID', 'restricted',
 'Halal 시장 의식 + 국가별 주류세 매우 높음. Aceh주는 무슬림에게 전면 금지.',
 'BPOM regulations; Aceh Qanun No.6/2014',
 null, 2014),
('alcohol', 'MY', 'restricted',
 '무슬림에게는 판매 금지(국적·종교 확인 필요). 비무슬림에게는 일반 판매 허용되나 광고 제한.',
 'Syariah Criminal Offences Acts (state-level); Customs Act 1967',
 null, null),
('alcohol', 'IN', 'restricted',
 '주(州)별 주류 정책 상이 — Bihar/Gujarat/Mizoram 등 일부 주는 사실상 전면 금지.',
 'State Excise Acts (Bihar Prohibition Act 2016 등)',
 null, 2016),

-- ──────────────────────────────────────────────────────────────────
-- CANNABIS / CBD
-- ──────────────────────────────────────────────────────────────────
('cannabis_cbd', 'SG', 'banned',
 'THC·CBD 모두 마약류 통제 약물로 분류, 제품·소지 모두 금지.',
 'Misuse of Drugs Act (Singapore)',
 null, null),
('cannabis_cbd', 'KR', 'banned',
 'THC·CBD 모두 마약류 관리에 관한 법률에 따라 의료용 외에는 모든 제품이 금지됩니다.',
 '마약류 관리에 관한 법률',
 null, null),
('cannabis_cbd', 'JP', 'banned',
 '대마초 제품 일체 금지. CBD 도 THC 0.0% 검출 한도가 매우 엄격.',
 'Cannabis Control Act (Japan)',
 null, null),
('cannabis_cbd', 'CN', 'banned',
 '의료용 외 모든 대마 관련 제품 금지.',
 'PRC Public Security Administration Punishment Law',
 null, null),
('cannabis_cbd', 'SA', 'banned',
 '대마 일체 금지. 사형까지 가능한 마약 분류.',
 'Saudi Arabia Anti-Drug Law',
 null, null),
('cannabis_cbd', 'AE', 'banned',
 '대마 제품 일체 금지. CBD 화장품도 입국 금지.',
 'UAE Federal Law No.30/2021 on Combating Narcotics',
 null, 2021),
('cannabis_cbd', 'MY', 'banned',
 'THC·CBD 모두 마약류 통제 약물.',
 'Dangerous Drugs Act 1952',
 null, 1952),
('cannabis_cbd', 'ID', 'banned',
 'Narkotika Class I — 사형까지 가능.',
 'Indonesian Narcotics Law No.35/2009',
 null, 2009),
('cannabis_cbd', 'TH', 'restricted',
 '2022년 부분 합법화 후 2024년 재규제 — 의료용에 한정, 레크리에이션 제품 금지.',
 'Cannabis and Hemp Act re-regulation 2024',
 null, 2024),
('cannabis_cbd', 'US', 'restricted',
 '연방법상 마리화나 Schedule I, 그러나 주별로 의료·기호용 합법화 다양. CBD는 0.3% THC 미만 합법.',
 '2018 Farm Bill; state-level laws',
 null, 2018),

-- ──────────────────────────────────────────────────────────────────
-- GAMBLING / BETTING
-- ──────────────────────────────────────────────────────────────────
('gambling', 'CN', 'banned',
 '대륙 본토 모든 도박 금지 (마카오·홍콩 제외).',
 'Criminal Law of the PRC',
 null, null),
('gambling', 'SA', 'banned',
 '이슬람 율법에 따라 모든 도박 금지.',
 'Saudi Arabian Law',
 null, null),
('gambling', 'AE', 'banned',
 '도박 일체 금지 (관광객 카지노 포함). 2025년 일부 정책 변화 예정이나 현재 금지.',
 'UAE Federal Penal Code',
 null, null),
('gambling', 'KR', 'restricted',
 '내국인 카지노는 강원랜드 1곳만 허용. 온라인 도박/베팅 사실상 금지.',
 '관광진흥법, 형법',
 null, null),
('gambling', 'JP', 'restricted',
 '경마·경륜·복권 등 정부 운영 외 도박 금지. 카지노는 IR 통합형만 허용 (2027 개장 예정).',
 '刑法第185条; 統合型リゾート整備法',
 null, null),
('gambling', 'IN', 'restricted',
 '주별 정책 상이. 온라인 게임 GST 28% 부과 (2023).',
 'Public Gambling Act 1867; State laws',
 null, 2023),

-- ──────────────────────────────────────────────────────────────────
-- CRYPTOCURRENCY / CRYPTO ASSETS
-- ──────────────────────────────────────────────────────────────────
('crypto_finance', 'CN', 'banned',
 '암호화폐 거래·채굴·관련 서비스 일체 금지.',
 'PBoC + 9-부처 합동 발표 (2021)',
 null, 2021),
('crypto_finance', 'SA', 'restricted',
 'SAMA 가 비공식적으로 거래소 운영 금지하나 개인 보유는 회색 지대.',
 'Saudi Central Bank (SAMA) advisory',
 null, null),
('crypto_finance', 'IN', 'restricted',
 '거래는 합법이지만 30% 양도소득세 + 1% TDS 부과로 사실상 위축.',
 'Finance Act 2022',
 null, 2022),
('crypto_finance', 'KR', 'restricted',
 '거래소 등록 의무, ICO 금지, 익명 거래 금지.',
 '특정금융정보법 (특금법)',
 null, 2021),
('crypto_finance', 'VN', 'restricted',
 '결제 수단으로 인정 불가 (현재까지). 거래는 회색 지대.',
 'State Bank of Vietnam circulars',
 null, null),

-- ──────────────────────────────────────────────────────────────────
-- TOBACCO (담배)
-- ──────────────────────────────────────────────────────────────────
('tobacco', 'SA', 'restricted',
 '단순 광고·플레인 패키징 의무 + 100% 수입세 적용.',
 'Saudi Arabia Tobacco Control Law',
 null, null),
('tobacco', 'AU', 'restricted',
 '플레인 패키징 의무 (세계 최초), 광고 일체 금지.',
 'Tobacco Plain Packaging Act 2011',
 null, 2011),
('tobacco', 'SG', 'restricted',
 '플레인 패키징 의무 (2020년부터). 광고 전면 금지.',
 'Smoking (Control of Advertisements and Sale) Act',
 null, 2020),

-- ──────────────────────────────────────────────────────────────────
-- DIETARY SUPPLEMENT / 건강기능식품
-- ──────────────────────────────────────────────────────────────────
('dietary_supplement', 'KR', 'restricted',
 '식약처(MFDS) 건강기능식품 인증 또는 일반식품 신고 필수. 효능 표방 시 별도 허가.',
 '건강기능식품에 관한 법률',
 'https://www.mfds.go.kr', null),
('dietary_supplement', 'JP', 'restricted',
 '특정보건용식품(特保) 또는 기능성표시식품 신고 필요. 일반식품으로는 효능 표방 불가.',
 '消費者庁機能性表示食品制度',
 null, 2015),
('dietary_supplement', 'CN', 'restricted',
 '건강식품(保健食品) 등록 필수, 외국 제조 시 공장 등록 + 약 1~3년 등록 절차.',
 'CFDA / 国家市场监督管理总局',
 null, null),
('dietary_supplement', 'SA', 'restricted',
 'SFDA 등록 + Halal 권장. 표시법 매우 엄격.',
 'SFDA Health Products Regulations',
 null, null),
('dietary_supplement', 'AE', 'restricted',
 '두바이 보건부(DHA) / MoHAP 등록 필수.',
 'UAE Ministry of Health and Prevention regulations',
 null, null),

-- ──────────────────────────────────────────────────────────────────
-- ADULT CONTENT
-- ──────────────────────────────────────────────────────────────────
('adult_content', 'SA', 'banned',
 '성인용 콘텐츠 일체 차단 (정부 차원의 인터넷 필터링).',
 'Communications and Information Technology Commission (CITC)',
 null, null),
('adult_content', 'AE', 'banned',
 '성인용 콘텐츠 차단. VPN 사용도 제한.',
 'UAE Federal Cybercrime Law',
 null, null),
('adult_content', 'CN', 'banned',
 '성인 콘텐츠 일체 검열·차단.',
 'Cyberspace Administration of China',
 null, null),
('adult_content', 'KR', 'restricted',
 '음란물 유통은 형사 처벌 대상 (성인 인증 + 청불 분류 필수).',
 '정보통신망법, 형법',
 null, null),
('adult_content', 'IN', 'restricted',
 '성인 사이트 800여 개 차단 명령 (2018), 일부 우회 가능.',
 'Information Technology Act 2000',
 null, 2018),

-- ──────────────────────────────────────────────────────────────────
-- FIREARMS
-- ──────────────────────────────────────────────────────────────────
('firearms', 'JP', 'banned',
 '민간 화기 소유 사실상 전면 금지 (수렵용 산탄총 매우 제한적 허가).',
 '銃砲刀剣類所持等取締法',
 null, null),
('firearms', 'KR', 'banned',
 '민간 화기 소유 금지 (사냥용 보관도 경찰서 위탁 보관).',
 '총포·도검·화약류 등의 안전관리에 관한 법률',
 null, null),
('firearms', 'SG', 'banned',
 '민간 화기 소지·수입·판매 모두 금지.',
 'Arms and Explosives Act',
 null, null),
('firearms', 'CN', 'banned',
 '민간 화기 소지 일체 금지.',
 'Law on Control of Firearms',
 null, null),
('firearms', 'AE', 'restricted',
 '내무부 허가증 필수. 외국인 소유 매우 제한적.',
 'UAE Federal Law No.3/2009 on Firearms',
 null, 2009),

-- ──────────────────────────────────────────────────────────────────
-- PHARMACEUTICAL (처방약 / OTC 약품)
-- ──────────────────────────────────────────────────────────────────
('pharmaceutical', 'KR', 'restricted',
 '식약처(MFDS) 의약품 허가 필수. 일반의약품도 약국 외 판매 제한.',
 '약사법, 의약품 등의 안전에 관한 규칙',
 null, null),
('pharmaceutical', 'JP', 'restricted',
 'PMD Act 의약품 승인 필수. 직판은 주로 약국 채널.',
 '医薬品、医療機器等の品質、有効性及び安全性の確保等に関する法律',
 null, 2014),
('pharmaceutical', 'CN', 'restricted',
 'NMPA 의약품 등록 + 외국 제조 공장 GMP 인증 필수.',
 '中华人民共和国药品管理法',
 null, null),
('pharmaceutical', 'US', 'restricted',
 'FDA 승인 필수 (NDA / ANDA / 510(k) 등). 광고 매우 엄격.',
 'Federal Food, Drug, and Cosmetic Act',
 null, null),
('pharmaceutical', 'EU', 'restricted',
 'EMA 중앙 승인 또는 회원국별 승인 필수.',
 'EU Regulation (EC) No 726/2004',
 null, 2004),
('pharmaceutical', 'SA', 'restricted',
 'SFDA 의약품 등록 필수.',
 'Saudi Food and Drug Authority Drug Regulations',
 null, null)

on conflict (regulated_category, country_code) do update set
  status = excluded.status,
  reason = excluded.reason,
  source = excluded.source,
  source_url = excluded.source_url,
  effective_year = excluded.effective_year,
  fetched_at = now();
