-- category_competitors seed — major brands per (category, country) cell.
--
-- Coverage strategy: focus on cells where B2B users are most likely to
-- run simulations. Skip exotic combinations (e.g. SaaS in SA, fashion
-- in CN) where the competitive context is either thin or different
-- enough that we'd rather have the LLM extrapolate than fix bad data.
--
-- 4-5 brands per cell. brand_role assigns each one a strategic anchor
-- (leader / challenger / value / premium / niche / local-hero) so the
-- LLM frames the landscape correctly without re-extracting it from
-- the cultural_notes blob every time.

insert into public.category_competitors
  (category, country_code, brand_name, brand_role, segment, notes, source)
values

-- ──────────────────────────────────────────────────────────────────
-- BEAUTY  (skincare, cosmetics, K/J-beauty, prestige)
-- ──────────────────────────────────────────────────────────────────
('beauty', 'KR', 'Olive Young', 'leader', 'mass',
 'Health & beauty retailer with ~70% market share in offline beauty channel; strong online via Olive Young Mall.',
 'Euromonitor / Olive Young IR'),
('beauty', 'KR', 'AmorePacific', 'leader', 'premium',
 'Domestic conglomerate (Sulwhasoo, Innisfree, Laneige). Premium tier; strong department store presence.',
 'Euromonitor KR Beauty'),
('beauty', 'KR', 'LG H&H', 'challenger', 'premium',
 'The history of Whoo, OHUI; competes with AmorePacific in luxury skincare. Strong China export.',
 'Euromonitor KR Beauty'),
('beauty', 'KR', 'CJ Olive Young Brands', 'value', 'mass',
 'Wakemake, Round Lab, etc. — fast-rising indie K-beauty seeded through Olive Young distribution.',
 'Olive Young IR'),
('beauty', 'KR', 'Sephora Korea', 'niche', 'premium',
 'Entered 2020. Foreign prestige brands (Charlotte Tilbury, Fenty). Limited footprint vs Olive Young.',
 'Sephora Asia'),
('beauty', 'JP', 'Shiseido', 'leader', 'premium',
 'Domestic giant; Shiseido / Clé de Peau / Nars. Strong department store and prestige channel.',
 'Euromonitor JP Beauty'),
('beauty', 'JP', 'Kao', 'challenger', 'mass',
 'Biore, Curel, Kanebo. Mass + skincare derma. Drugstore chain dominance.',
 'Euromonitor JP Beauty'),
('beauty', 'JP', '@cosme', 'niche', 'mass',
 'Most influential review platform; @cosme store offline rollout.',
 '@cosme insights report'),
('beauty', 'JP', 'Matsumoto Kiyoshi', 'value', 'mass',
 'Largest drugstore chain. PB brands (Argelan) growing.',
 'Nielsen JP Drugstore'),
('beauty', 'CN', 'Proya', 'leader', 'mass',
 'Domestic skincare leader since 2022, surpassing L''Oreal in some categories.',
 '艾媒咨询 China Beauty'),
('beauty', 'CN', 'Perfect Diary (Yatsen)', 'challenger', 'value',
 'DTC color cosmetics darling; heavy KOL marketing on Xiaohongshu / Douyin.',
 'Yatsen Holding IR'),
('beauty', 'CN', 'L''Oreal China', 'challenger', 'premium',
 'Global #2 globally but losing share to local brands; strong Tmall flagship.',
 'L''Oreal Quarterly Report'),
('beauty', 'CN', 'Estee Lauder China', 'niche', 'luxury',
 'Estee, MAC, La Mer. Premium tier; weakened by post-2023 local-brand surge.',
 'Estee Lauder IR'),
('beauty', 'US', 'Sephora', 'leader', 'premium',
 'Owned by LVMH; ~2,700 stores globally. Anchor of US prestige beauty.',
 'LVMH Annual Report'),
('beauty', 'US', 'Ulta Beauty', 'challenger', 'mass',
 '~1,300 stores, mass + masstige. Strong loyalty program. Targets a wider demographic than Sephora.',
 'Ulta Beauty IR'),
('beauty', 'US', 'e.l.f. Cosmetics', 'value', 'value',
 'Affordable-luxe leader, strong Gen-Z TikTok presence; market cap surge 2023-2024.',
 'e.l.f. Beauty IR'),
('beauty', 'US', 'Glossier / Fenty / Rare Beauty', 'niche', 'premium',
 'DTC indie premium brands with massive social proof. Sell direct + Sephora.',
 'Industry analysts'),
('beauty', 'GB', 'Boots', 'leader', 'mass',
 'Walgreens-owned high street pharmacy / beauty. ~2,200 stores.',
 'WBA Annual Report'),
('beauty', 'GB', 'Space NK', 'challenger', 'premium',
 'UK prestige beauty retailer; ~83 stores plus online. Curated selection.',
 'Industry data'),
('beauty', 'GB', 'Charlotte Tilbury', 'niche', 'premium',
 'British heritage brand; iconic Pillow Talk lipstick. Acquired by Puig 2020.',
 'Puig IR'),
('beauty', 'GB', 'Cult Beauty / LookFantastic', 'challenger', 'mass',
 'Large online beauty retailers with subscription boxes. Owned by THG.',
 'THG IR'),
('beauty', 'FR', 'Sephora France', 'leader', 'premium',
 'LVMH home market; ~360 stores in France. Anchor for prestige beauty.',
 'LVMH Annual Report'),
('beauty', 'FR', 'L''Oreal Paris', 'challenger', 'mass',
 'Global headquarters; strongest mass-market presence. Garnier, Maybelline.',
 'L''Oreal Annual Report'),
('beauty', 'FR', 'Marionnaud / Nocibé', 'challenger', 'mass',
 'Major perfumeries chains. ~600 stores combined.',
 'Industry data'),
('beauty', 'FR', 'La Roche-Posay / Vichy', 'niche', 'premium',
 'Pharmacy-grade dermo-cosmetic leaders. Owned by L''Oreal.',
 'L''Oreal Annual Report'),
('beauty', 'SG', 'Sephora SG', 'leader', 'premium',
 'Anchor regional prestige hub.',
 'Sephora SE Asia'),
('beauty', 'SG', 'Watsons', 'challenger', 'mass',
 'Health & beauty chain ~120 stores; AS Watson group.',
 'AS Watson IR'),
('beauty', 'SG', 'Sasa', 'value', 'mass',
 'Hong Kong–origin chain; competes on multi-brand discount.',
 'Sasa IR'),
('beauty', 'AE', 'Faces', 'leader', 'premium',
 'Regional premium beauty retailer headquartered in Dubai. ~150+ stores in MENA.',
 'Chalhoub Group IR'),
('beauty', 'AE', 'Sephora ME', 'challenger', 'premium',
 'LVMH MENA arm; ~50 stores.',
 'LVMH MENA'),
('beauty', 'SA', 'Faces', 'leader', 'premium',
 'Same regional leader; dominant in Riyadh/Jeddah malls.',
 'Chalhoub Group IR'),
('beauty', 'SA', 'Nice One', 'challenger', 'mass',
 'Saudi homegrown e-commerce beauty; rapid growth post-Vision 2030.',
 'Saudi e-commerce reports'),

-- ──────────────────────────────────────────────────────────────────
-- ELECTRONICS  (consumer electronics, smartphones, audio, wearables)
-- ──────────────────────────────────────────────────────────────────
('electronics', 'KR', 'Samsung Electronics', 'leader', 'premium',
 'Domestic dominance — 70%+ smartphone share; full appliance + Galaxy Buds.',
 'IDC Korea / Samsung IR'),
('electronics', 'KR', 'LG Electronics', 'challenger', 'premium',
 'Strong appliance + TV; smaller smartphone presence (exited 2021).',
 'LG Electronics IR'),
('electronics', 'KR', 'Apple Korea', 'challenger', 'premium',
 '~25% smartphone share, growing among Gen-Z. AirPods strong audio.',
 'IDC Korea'),
('electronics', 'KR', 'Coupang', 'niche', 'mass',
 'Dominant electronics e-commerce; same-day delivery. Often the #1 channel.',
 'Coupang IR'),
('electronics', 'JP', 'Sony', 'leader', 'premium',
 'Headphones (WH-1000XM), gaming (PlayStation), cameras. Premium audio leader.',
 'Sony Group IR'),
('electronics', 'JP', 'Panasonic', 'challenger', 'mass',
 'Strong appliances + B2B electronics. Smartphones absent.',
 'Panasonic IR'),
('electronics', 'JP', 'Apple Japan', 'leader', 'premium',
 'Largest smartphone share (~50%); AirPods de facto wireless audio.',
 'IDC Japan'),
('electronics', 'JP', 'Yodobashi / Bic Camera', 'niche', 'mass',
 'Major specialty retailers; physical anchor for tech purchase decisions.',
 'Industry data'),
('electronics', 'CN', 'Xiaomi', 'leader', 'value',
 'Smartphone, IoT ecosystem; strong AIoT + smart home strategy.',
 'Xiaomi IR'),
('electronics', 'CN', 'Huawei / Honor', 'challenger', 'premium',
 'Resurgent post-2023 with Mate60 launch; flagship ecosystem.',
 '艾媒咨询'),
('electronics', 'CN', 'Apple China', 'challenger', 'luxury',
 '~17% smartphone share; premium tier under increasing local pressure.',
 'IDC China'),
('electronics', 'CN', 'JD / Tmall Electronics', 'niche', 'mass',
 'Top e-commerce channels; JD known for authentic-only logistics.',
 'JD.com / Alibaba IR'),
('electronics', 'TW', 'Acer / Asus', 'leader', 'premium',
 'Domestic giants in laptops + gaming hardware. Global brands HQ''d in TW.',
 'Acer / Asus IR'),
('electronics', 'TW', 'PChome / momo', 'niche', 'mass',
 'Top e-commerce platforms. PChome 24-hour delivery iconic.',
 'TW e-commerce reports'),
('electronics', 'TW', 'Apple TW', 'challenger', 'premium',
 '~30% smartphone share; Apple Premium Reseller network.',
 'IDC Taiwan'),
('electronics', 'US', 'Apple', 'leader', 'premium',
 '~57% smartphone share, AirPods de facto wireless audio. Apple Store retail.',
 'Counterpoint / Apple IR'),
('electronics', 'US', 'Samsung US', 'challenger', 'premium',
 'Galaxy ecosystem; Best Buy + carriers + Samsung Store.',
 'Samsung IR'),
('electronics', 'US', 'Sony', 'niche', 'premium',
 'Audio (WH-1000XM, WF-1000XM) - major wireless earbuds challenger to AirPods.',
 'Sony Group IR'),
('electronics', 'US', 'Bose', 'niche', 'premium',
 'Premium audio specialist; QuietComfort earbuds compete with AirPods Pro.',
 'Industry data'),
('electronics', 'US', 'Best Buy / Amazon', 'niche', 'mass',
 'Top electronics retail (Best Buy ~1,000 stores) + e-commerce (Amazon).',
 'Industry data'),
('electronics', 'GB', 'Apple UK', 'leader', 'premium',
 '~50% smartphone share; Apple Stores anchor London/Manchester.',
 'IDC UK / Apple IR'),
('electronics', 'GB', 'Samsung UK', 'challenger', 'premium',
 'Galaxy ecosystem; Currys + carriers.',
 'Samsung IR'),
('electronics', 'GB', 'Currys', 'niche', 'mass',
 'Largest specialty electronics retailer (~300 stores).',
 'Currys IR'),
('electronics', 'GB', 'John Lewis', 'niche', 'premium',
 'Premium department store; strong electronics sub-segment with longer warranties.',
 'John Lewis Partnership IR'),
('electronics', 'DE', 'Apple Germany', 'leader', 'premium',
 '~30% smartphone share; Apple Store + Premium Reseller network.',
 'IDC Germany'),
('electronics', 'DE', 'Samsung DE', 'challenger', 'premium',
 'Largest smartphone share ~35%; MediaMarkt + Saturn anchor.',
 'IDC Germany'),
('electronics', 'DE', 'MediaMarkt / Saturn', 'leader', 'mass',
 'Combined CECONOMY largest electronics retail in Europe.',
 'CECONOMY IR'),
('electronics', 'DE', 'Bosch / Siemens', 'niche', 'premium',
 'Major appliance brands; smaller in personal electronics.',
 'BSH IR'),
('electronics', 'SG', 'Apple SG', 'leader', 'premium',
 'Apple Marina Bay flagship + 4 stores; ~40% smartphone share.',
 'IDC SG'),
('electronics', 'SG', 'Samsung SG', 'challenger', 'premium',
 'Galaxy ecosystem; Challenger / Best Denki distribution.',
 'IDC SG'),
('electronics', 'SG', 'Lazada / Shopee', 'niche', 'mass',
 'Top regional e-commerce, electronics is a huge category.',
 'IDC SG'),

-- ──────────────────────────────────────────────────────────────────
-- FASHION  (apparel, footwear, accessories)
-- ──────────────────────────────────────────────────────────────────
('fashion', 'KR', 'Musinsa', 'leader', 'mass',
 'Largest fashion e-commerce platform; anchor for menswear and street.',
 'Musinsa IR'),
('fashion', 'KR', 'Zigzag / W Concept', 'challenger', 'mass',
 'Womenswear-focused platforms. Both acquired by Kakao.',
 'Kakao IR'),
('fashion', 'KR', 'Uniqlo / GU', 'challenger', 'value',
 'Fast Retailing JV; strong basics presence post-2019 boycott recovery.',
 'Fast Retailing IR'),
('fashion', 'KR', '8seconds / SPAO', 'value', 'value',
 'Domestic SPA brands; competition with Uniqlo for value tier.',
 'Industry data'),
('fashion', 'JP', 'Uniqlo', 'leader', 'value',
 'Domestic giant; cornerstone of Fast Retailing.',
 'Fast Retailing IR'),
('fashion', 'JP', 'ZOZOTOWN', 'leader', 'mass',
 'Largest fashion e-commerce; ~10M MAU. Acquired by Yahoo (Z Holdings).',
 'ZOZO IR'),
('fashion', 'JP', 'Beams / United Arrows', 'niche', 'premium',
 'Curated select shop chains; strong in premium menswear / lifestyle.',
 'Industry data'),
('fashion', 'US', 'Nike', 'leader', 'premium',
 'Sportswear leader; DTC accelerated post-2020.',
 'Nike IR'),
('fashion', 'US', 'Lululemon', 'challenger', 'premium',
 'Athleisure giant; women + premium men''s growth.',
 'Lululemon IR'),
('fashion', 'US', 'SHEIN', 'value', 'value',
 'Ultra-fast-fashion disruptor; #1 fashion app downloads 2022-2024.',
 'App Annie / SimilarWeb'),
('fashion', 'US', 'Amazon Fashion', 'challenger', 'mass',
 'Largest US apparel e-commerce; Prime Wardrobe.',
 'Industry data'),
('fashion', 'GB', 'ASOS', 'leader', 'mass',
 'Online-only fashion giant; strong own-brand portfolio.',
 'ASOS IR'),
('fashion', 'GB', 'Primark', 'value', 'value',
 'Value fast-fashion offline anchor; ~440 stores.',
 'AB Foods IR'),
('fashion', 'GB', 'Marks & Spencer', 'niche', 'premium',
 'Department store; quality basics + food.',
 'M&S IR'),
('fashion', 'FR', 'Zara / Bershka', 'leader', 'mass',
 'Inditex brands; fast-fashion dominant.',
 'Inditex IR'),
('fashion', 'FR', 'LVMH brands', 'leader', 'luxury',
 'Louis Vuitton, Dior, Celine — luxury fashion HQ market.',
 'LVMH Annual Report'),
('fashion', 'FR', 'Galeries Lafayette / Printemps', 'niche', 'premium',
 'Grand magasin department stores; Paris flagship anchors.',
 'Industry data'),
('fashion', 'SG', 'Zalora', 'leader', 'mass',
 'SE Asia online fashion leader. ~10M users across 6 markets.',
 'Zalora press releases'),
('fashion', 'SG', 'Charles & Keith', 'leader', 'premium',
 'Iconic Singapore-origin global accessories brand.',
 'Charles & Keith corporate'),
('fashion', 'SG', 'Love Bonito', 'challenger', 'premium',
 'SG-origin DTC womenswear; localized for Asian fits.',
 'Love Bonito press'),
('fashion', 'MY', 'Padini Holdings', 'leader', 'mass',
 'Domestic apparel group: Padini, Vincci, SEED, Brands Outlet.',
 'Padini IR'),
('fashion', 'MY', 'Zalora MY', 'challenger', 'mass',
 'Regional online fashion leader.',
 'Zalora SE Asia'),
('fashion', 'MY', 'Uniqlo MY', 'challenger', 'value',
 'Strong basics presence in KL malls.',
 'Fast Retailing IR'),

-- ──────────────────────────────────────────────────────────────────
-- FOOD  (F&B, packaged food, grocery)
-- ──────────────────────────────────────────────────────────────────
('food', 'KR', 'CJ CheilJedang', 'leader', 'premium',
 'Bibigo, Hetbahn — global leader in K-food packaged. Strong export.',
 'CJ IR'),
('food', 'KR', 'Lotte Food', 'challenger', 'mass',
 'Wide F&B portfolio (Lotte Mart, Lotteria, etc.).',
 'Lotte IR'),
('food', 'KR', 'Coupang Eats / Baemin', 'niche', 'mass',
 'Top food delivery apps. Baemin (Woowa Brothers) #1 with ~70% share.',
 'Industry analyst reports'),
('food', 'JP', 'Aeon', 'leader', 'mass',
 'Largest grocery retailer chain in Japan; PB Top Valu.',
 'Aeon IR'),
('food', 'JP', 'Seven & i', 'leader', 'mass',
 'Seven-Eleven, Ito-Yokado, Sogo. Convenience store dominance.',
 'Seven & i IR'),
('food', 'JP', 'Calbee / Meiji', 'leader', 'mass',
 'Snack + dairy giants. Strong domestic brand loyalty.',
 'Industry data'),
('food', 'US', 'Walmart', 'leader', 'value',
 'Largest grocery retailer ~$650B sales 2023.',
 'Walmart IR'),
('food', 'US', 'Whole Foods (Amazon)', 'niche', 'premium',
 'Premium organic; ~530 stores. Amazon Prime integration.',
 'Amazon IR'),
('food', 'US', 'Costco / Trader Joe''s', 'leader', 'value',
 'Membership warehouse + curated grocery anchors.',
 'Costco IR'),
('food', 'US', 'DoorDash / UberEats', 'niche', 'mass',
 'Top food delivery; DoorDash ~65% share US restaurant delivery.',
 'Industry data'),
('food', 'GB', 'Tesco', 'leader', 'mass',
 'Largest grocery chain; ~27% UK market share.',
 'Tesco IR'),
('food', 'GB', 'Sainsbury''s / Asda / Morrisons', 'challenger', 'mass',
 'Big-4 supermarkets after Tesco.',
 'Industry data'),
('food', 'GB', 'M&S Food', 'niche', 'premium',
 'Premium prepared food; iconic for ready meals.',
 'M&S IR'),
('food', 'AE', 'Carrefour UAE', 'leader', 'mass',
 'Operated by Majid Al Futtaim; largest hypermarket chain.',
 'MAF Holding IR'),
('food', 'AE', 'Lulu Hypermarket', 'leader', 'mass',
 'GCC chain ~250 stores; strong pan-GCC presence.',
 'EMKE Group press'),
('food', 'AE', 'Talabat / Careem', 'niche', 'mass',
 'Top food delivery apps in Gulf.',
 'Industry data'),
('food', 'SA', 'Lulu Hypermarket', 'leader', 'mass',
 'Largest hypermarket chain in KSA.',
 'EMKE Group'),
('food', 'SA', 'Panda / Tamimi / Carrefour KSA', 'challenger', 'mass',
 'Major supermarket chains; modern grocery dominates.',
 'Industry data'),
('food', 'SA', 'HungerStation / Jahez / ToYou', 'niche', 'mass',
 'Leading food delivery — local Jahez listed Tadawul 2022.',
 'Jahez IR'),
('food', 'MY', 'Aeon Malaysia', 'leader', 'mass',
 'Largest Japanese-origin hypermarket chain.',
 'Aeon MY IR'),
('food', 'MY', 'Tesco / Lotus''s', 'challenger', 'mass',
 'Renamed Lotus''s 2021 after CP Group takeover.',
 'CP Group IR'),
('food', 'MY', 'GrabFood / FoodPanda', 'niche', 'mass',
 'Top food delivery apps; Grab dominant.',
 'Industry data'),

-- ──────────────────────────────────────────────────────────────────
-- HEALTH (supplements, OTC, functional foods)
-- ──────────────────────────────────────────────────────────────────
('health', 'KR', 'Korea Ginseng Corp (정관장)', 'leader', 'premium',
 'Ginseng category leader; Cheong Kwan Jang brand.',
 'Korea Ginseng Corp'),
('health', 'KR', 'CJ HealthCare / Daewoong', 'challenger', 'mass',
 'Major pharma + functional foods.',
 'Industry data'),
('health', 'KR', 'Olive Young Health', 'niche', 'mass',
 'Health & wellness section now anchors omnichannel.',
 'Olive Young IR'),
('health', 'JP', 'Otsuka', 'leader', 'mass',
 'Pocari Sweat, Calorie Mate. Functional drinks leader.',
 'Otsuka IR'),
('health', 'JP', 'Yakult', 'leader', 'mass',
 'Probiotic drinks; iconic global brand.',
 'Yakult IR'),
('health', 'JP', 'Matsumoto Kiyoshi (drugstore)', 'niche', 'mass',
 'Largest drugstore chain anchors OTC + supplements.',
 'Industry data'),
('health', 'US', 'GNC', 'leader', 'mass',
 'Specialty supplement retailer.',
 'GNC IR'),
('health', 'US', 'Vitamin Shoppe / iHerb', 'challenger', 'mass',
 'Online supplement giants.',
 'Industry data'),
('health', 'US', 'Nature Made / NOW Foods', 'niche', 'mass',
 'Mass supplement brands; available at all major retailers.',
 'Industry data'),
('health', 'GB', 'Holland & Barrett', 'leader', 'mass',
 'Largest health & wellness retailer (~750 stores).',
 'H&B IR'),
('health', 'GB', 'Boots Health', 'challenger', 'mass',
 'Pharmacy-chain health anchor.',
 'Walgreens Boots Alliance IR'),

-- ──────────────────────────────────────────────────────────────────
-- SAAS  (B2B software, productivity)
-- ──────────────────────────────────────────────────────────────────
('saas', 'US', 'Salesforce', 'leader', 'premium',
 'CRM standard; ecosystem of vertical apps.',
 'Salesforce IR'),
('saas', 'US', 'Microsoft (Office 365)', 'leader', 'premium',
 'Enterprise standard; ~400M paid seats globally.',
 'Microsoft IR'),
('saas', 'US', 'HubSpot / Notion / Slack', 'challenger', 'mass',
 'Mid-market and SMB favorites; product-led growth playbook.',
 'Industry analysts'),
('saas', 'US', 'AWS Marketplace', 'niche', 'mass',
 'Distribution channel for B2B software in cloud-first stacks.',
 'AWS'),
('saas', 'GB', 'Salesforce UK', 'leader', 'premium',
 'Same global standard.',
 'Salesforce IR'),
('saas', 'GB', 'Sage', 'leader', 'mass',
 'UK accounting software giant; SMB ERP leader.',
 'Sage IR'),
('saas', 'GB', 'Xero', 'challenger', 'mass',
 'NZ-origin cloud accounting; strong UK SMB presence.',
 'Xero IR'),
('saas', 'KR', '네이버 클라우드 / 카카오엔터프라이즈', 'leader', 'mass',
 'Local hyperscalers; gov + chaebol-friendly procurement.',
 'Industry data'),
('saas', 'KR', 'Salesforce Korea', 'challenger', 'premium',
 'Foreign SaaS leader; weighted to large enterprise.',
 'Industry data'),
('saas', 'KR', 'Saramin / Wanted', 'niche', 'mass',
 'HR-tech leaders. Local-language focus.',
 'Industry data'),
('saas', 'JP', 'Salesforce JP', 'leader', 'premium',
 'CRM / sales standard for enterprise.',
 'Salesforce IR'),
('saas', 'JP', 'freee / Money Forward', 'leader', 'mass',
 'Domestic accounting / fintech SaaS; SMB market leaders.',
 'freee / MF IR'),
('saas', 'JP', 'Cybozu (kintone)', 'challenger', 'mass',
 'Workflow / business apps; popular with mid-market.',
 'Cybozu IR'),
('saas', 'SG', 'Salesforce SG', 'leader', 'premium',
 'Regional HQ for ASEAN.',
 'Salesforce IR'),
('saas', 'SG', 'AWS Singapore', 'leader', 'premium',
 'Largest AWS region in SEA.',
 'AWS'),
('saas', 'SG', 'PropertyGuru / Lazada B2B', 'niche', 'mass',
 'Local-focused vertical SaaS leaders.',
 'Industry data')

on conflict (category, country_code, brand_name) do update set
  brand_role = excluded.brand_role,
  segment = excluded.segment,
  notes = excluded.notes,
  source = excluded.source,
  fetched_at = now();
