import { NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import { getOrCreatePrimaryWorkspace } from "@/lib/workspace";
import { buildReportPdf } from "@/lib/report/pdf";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

const LABELS_BY_LOCALE: Record<string, Parameters<typeof buildReportPdf>[0]["labels"]> = {
  ko: {
    title: "출시 시뮬레이션 리포트",
    subtitle: "AI 페르소나 기반 시장 반응 예측",
    cover: {
      eyebrow: "MARKET TWIN · LAUNCH SIMULATION REPORT",
      successScore: "성공 확률",
      bestCountry: "추천 진출국",
      bestPrice: "추천 가격",
      bestSegment: "최적 타겟",
      riskLevel: "리스크",
      runDate: "분석일",
      personas: "페르소나 수",
      model: "AI 모델",
    },
    executiveSummary: "핵심 요약",
    keyMetrics: "주요 지표",
    countryRanking: "국가별 시장 매력도",
    countryCol: {
      rank: "순위",
      country: "국가",
      demand: "수요",
      comp: "경쟁",
      score: "점수",
    },
    pricingRecommendation: "가격 전략",
    pricingRecommendedPrice: "추천 가격",
    pricingMargin: "마진 추정",
    pricingCurve: "가격대별 전환·매출 곡선",
    pricingCol: {
      price: "가격",
      conversion: "전환율",
      revenue: "매출 지수",
    },
    personaInsights: "페르소나 인사이트",
    personaCount: "페르소나 수",
    personaAvgIntent: "평균 구매의향",
    personaHigh: "고의향 (≥70)",
    personaLow: "저의향 (<35)",
    personaByCountry: "국가별 분포",
    risks: "리스크 분석",
    actionPlan: "실행 액션 플랜",
    channels: "추천 채널",
    dataSources: "참고 데이터 출처",
    regulatoryTitle: "규제 검증",
    regulatoryExcluded: "판매 금지",
    regulatoryRestricted: "조건부 허용",
    generatedBy: "Generated by Market Twin",
    page: "페이지",
  },
  en: {
    title: "Launch Simulation Report",
    subtitle: "AI persona–based market reaction forecast",
    cover: {
      eyebrow: "MARKET TWIN · LAUNCH SIMULATION REPORT",
      successScore: "Success Score",
      bestCountry: "Best Country",
      bestPrice: "Recommended Price",
      bestSegment: "Best Segment",
      riskLevel: "Risk",
      runDate: "Run Date",
      personas: "Personas",
      model: "AI Model",
    },
    executiveSummary: "Executive Summary",
    keyMetrics: "Key Metrics",
    countryRanking: "Country Market Attractiveness",
    countryCol: {
      rank: "Rank",
      country: "Country",
      demand: "Demand",
      comp: "Comp.",
      score: "Score",
    },
    pricingRecommendation: "Pricing Strategy",
    pricingRecommendedPrice: "Recommended Price",
    pricingMargin: "Margin Estimate",
    pricingCurve: "Price vs Conversion / Revenue",
    pricingCol: {
      price: "Price",
      conversion: "Conversion",
      revenue: "Revenue index",
    },
    personaInsights: "Persona Insights",
    personaCount: "Persona Count",
    personaAvgIntent: "Avg Intent",
    personaHigh: "High (≥70)",
    personaLow: "Low (<35)",
    personaByCountry: "By Country",
    risks: "Risk Analysis",
    actionPlan: "Action Plan",
    channels: "Recommended Channels",
    dataSources: "Data Sources",
    regulatoryTitle: "Regulatory Check",
    regulatoryExcluded: "Banned",
    regulatoryRestricted: "Restricted",
    generatedBy: "Generated by Market Twin",
    page: "Page",
  },
};

export async function GET(
  req: Request,
  ctx: { params: Promise<{ simulationId: string }> },
) {
  const { simulationId } = await ctx.params;
  const url = new URL(req.url);
  const locale = url.searchParams.get("locale") === "en" ? "en" : "ko";

  const wsCtx = await getOrCreatePrimaryWorkspace();
  if (!wsCtx) return NextResponse.json({ error: "unauthorized" }, { status: 401 });

  const supabase = await createClient();
  const { data: sim, error: simErr } = await supabase
    .from("simulations")
    .select(
      "id, project_id, persona_count, started_at, completed_at, model_provider, model_version, projects(product_name)",
    )
    .eq("id", simulationId)
    .eq("workspace_id", wsCtx.workspaceId)
    .single();
  if (simErr || !sim) return NextResponse.json({ error: "not found" }, { status: 404 });

  const { data: result } = await supabase
    .from("simulation_results")
    .select("*")
    .eq("simulation_id", simulationId)
    .single();
  if (!result) return NextResponse.json({ error: "result not ready" }, { status: 409 });

  const productName = Array.isArray(sim.projects)
    ? (sim.projects[0] as { product_name?: string })?.product_name ?? ""
    : (sim.projects as { product_name?: string } | null)?.product_name ?? "";

  // _sources and _regulatory are added on persistence by the runner — extract
  // before passing to the schema-typed view.
  const overviewRaw = (result.overview ?? {}) as Record<string, unknown>;
  const sources: string[] = Array.isArray(overviewRaw._sources)
    ? (overviewRaw._sources as string[])
    : [];
  const regulatory =
    overviewRaw._regulatory && typeof overviewRaw._regulatory === "object"
      ? (overviewRaw._regulatory as {
          regulatedCategory?: string;
          warnings: { country: string; status: "banned" | "restricted" | "allowed"; reason?: string; source?: string }[];
        })
      : undefined;
  const { _sources, _regulatory, ...overviewClean } = overviewRaw;
  void _sources;
  void _regulatory;

  const completedAt = (sim as { completed_at?: string | null }).completed_at;
  const runDate = completedAt
    ? new Date(completedAt).toLocaleDateString(locale === "ko" ? "ko-KR" : "en-US", {
        year: "numeric",
        month: "short",
        day: "numeric",
      })
    : new Date().toLocaleDateString(locale === "ko" ? "ko-KR" : "en-US");

  const buffer = await buildReportPdf({
    result: {
      overview: overviewClean as never,
      countries: result.countries ?? [],
      personas: result.personas ?? [],
      pricing: result.pricing,
      creative: result.creative ?? [],
      risks: result.risks ?? [],
      recommendations: result.recommendations,
    },
    labels: LABELS_BY_LOCALE[locale],
    productName,
    sources,
    regulatory,
    locale,
    meta: {
      simulationId,
      runDate,
      personaCount: (sim as { persona_count?: number }).persona_count,
      modelProvider: (sim as { model_provider?: string | null }).model_provider,
      modelVersion: (sim as { model_version?: string | null }).model_version,
    },
  });

  // Track download (fire-and-forget)
  void supabase
    .from("reports")
    .insert({
      simulation_id: simulationId,
      workspace_id: wsCtx.workspaceId,
      format: "pdf",
      created_by: wsCtx.userId,
      download_count: 1,
    });

  return new NextResponse(buffer as unknown as BodyInit, {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="market-twin-${simulationId.slice(0, 8)}.pdf"`,
    },
  });
}
