import Anthropic from "@anthropic-ai/sdk";
import OpenAI from "openai";
import { toFile } from "openai/uploads";
import sharp from "sharp";
import { compositeLogoOnImage } from "./composite-logo";
import type { ImageGenSettings } from "./image-gen";

/**
 * Product-touchup mode — instead of asking gpt-image-1 to invent a
 * product from scratch (which keeps producing wrong silhouettes),
 * use one of the real library product photos AS THE BASE and only
 * regenerate the surrounding scene/background via image-edit + mask.
 *
 * Why this is more reliable than reference-only generation:
 *   • gpt-image-1.edit with a mask: opaque mask area = preserved pixels,
 *     transparent area = regenerated. So the product stays pixel-
 *     accurate and only the background changes.
 *   • No need to "describe the product" — the actual product pixels
 *     ARE the description.
 *   • Color, silhouette, materials, branding all 100% accurate because
 *     they're physically untouched.
 *
 * Flow per frame:
 *   1. Pick a library product photo (we get a different one per frame
 *      for variety when multiple uploaded).
 *   2. Use Claude vision to detect the product bbox.
 *   3. Build a sharp mask: opaque rectangle over the product (with 8%
 *      padding for blending), transparent everywhere else.
 *   4. Call openai.images.edit(image=product, mask=mask, prompt=scene).
 *   5. Optionally composite logo on top (sharp).
 */

export type TouchupResult = {
  base64: string;
  width: number;
  height: number;
  source_asset_url: string;
};

type BBox = { x: number; y: number; width: number; height: number };

async function detectProductBox(imageBuffer: Buffer): Promise<BBox | null> {
  if (!process.env.ANTHROPIC_API_KEY) return null;
  const downsized = await sharp(imageBuffer)
    .resize(1024, 1024, { fit: "inside", withoutEnlargement: true })
    .png()
    .toBuffer();
  const meta = await sharp(downsized).metadata();
  const dw = meta.width ?? 1024;
  const dh = meta.height ?? 1024;
  const fullMeta = await sharp(imageBuffer).metadata();
  const fw = fullMeta.width ?? dw;
  const fh = fullMeta.height ?? dh;
  const scaleX = fw / dw;
  const scaleY = fh / dh;

  const base64 = downsized.toString("base64");
  const client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });
  let resp;
  try {
    resp = await client.messages.create({
      model: "claude-sonnet-4-6",
      max_tokens: 300,
      system:
        "You output the bounding box of the MAIN product in the image. Respond with JSON only: {\"x\": number, \"y\": number, \"width\": number, \"height\": number} in pixels. The box should tightly enclose the product (no big margins). If multiple products visible, pick the largest/most central one. If no clear product, return all zeros.",
      messages: [
        {
          role: "user",
          content: [
            {
              type: "image",
              source: { type: "base64", media_type: "image/png", data: base64 },
            },
            { type: "text", text: "JSON only." },
          ],
        },
      ],
    });
  } catch {
    return null;
  }
  const text = resp.content
    .map((b) => (b.type === "text" ? b.text : ""))
    .filter(Boolean)
    .join("\n");
  const m = text.match(/\{[\s\S]*\}/);
  if (!m) return null;
  let parsed: Partial<BBox>;
  try {
    parsed = JSON.parse(m[0]);
  } catch {
    return null;
  }
  if (
    typeof parsed.x !== "number" ||
    typeof parsed.y !== "number" ||
    typeof parsed.width !== "number" ||
    typeof parsed.height !== "number" ||
    parsed.width < 10 ||
    parsed.height < 10
  ) {
    return null;
  }
  return {
    x: Math.round(parsed.x * scaleX),
    y: Math.round(parsed.y * scaleY),
    width: Math.round(parsed.width * scaleX),
    height: Math.round(parsed.height * scaleY),
  };
}

/**
 * Build a PNG mask for openai.images.edit:
 *   - OPAQUE black rectangle over product bbox (with padding) = preserved
 *   - TRANSPARENT everywhere else = regenerated by the model
 *
 * Per OpenAI spec, transparent alpha = "this area should be edited".
 */
async function buildPreservationMask(
  width: number,
  height: number,
  bbox: BBox,
  paddingPct = 8,
): Promise<Buffer> {
  const padX = Math.round((width * paddingPct) / 100);
  const padY = Math.round((height * paddingPct) / 100);
  const x = Math.max(0, bbox.x - padX);
  const y = Math.max(0, bbox.y - padY);
  const w = Math.min(width - x, bbox.width + padX * 2);
  const h = Math.min(height - y, bbox.height + padY * 2);
  // Use sharp to compose a transparent PNG with a single opaque rectangle.
  const svg = `<svg width="${width}" height="${height}" xmlns="http://www.w3.org/2000/svg">
    <rect x="${x}" y="${y}" width="${w}" height="${h}" fill="black"/>
  </svg>`;
  return sharp({
    create: {
      width,
      height,
      channels: 4,
      background: { r: 0, g: 0, b: 0, alpha: 0 },
    },
  })
    .composite([{ input: Buffer.from(svg) }])
    .png()
    .toBuffer();
}

export async function touchupProductImage(input: {
  sourceImageUrl: string;
  scenePrompt: string;
  outputSize: "1024x1024" | "1024x1536" | "1536x1024";
  quality: "low" | "medium" | "high";
  logoBuffer?: Buffer | null;
  logoOpts?: {
    position?:
      | "top-left"
      | "top-right"
      | "bottom-left"
      | "bottom-right"
      | "center";
    size_pct?: number;
    padding_pct?: number;
    opacity?: number;
    with_backdrop?: boolean;
  };
  /** When true and vision finds bbox, use mask-based preservation.
   *  When false or vision fails, falls back to plain image-edit (the
   *  model may still drift but at least references the source). */
  useMask?: boolean;
}): Promise<{
  buffer: Buffer;
  used_mask: boolean;
  mask_source: "vision" | "fallback" | "none";
} | null> {
  if (!process.env.OPENAI_API_KEY) {
    throw new Error("OPENAI_API_KEY not set");
  }
  // Fetch source
  const res = await fetch(input.sourceImageUrl);
  if (!res.ok) {
    throw new Error(`source fetch failed: ${res.status}`);
  }
  let sourceBuffer: Buffer = Buffer.from(await res.arrayBuffer()) as Buffer;
  // Resize source to match outputSize so masks align cleanly.
  const [outW, outH] = input.outputSize.split("x").map(Number);
  sourceBuffer = (await sharp(sourceBuffer)
    .resize(outW, outH, { fit: "cover", position: "center" })
    .png()
    .toBuffer()) as Buffer;

  // Build mask. Vision-detected bbox preferred, but if vision fails
  // we use a centered fallback (60-70% of frame) — better than no mask,
  // which would let the model invent a new product.
  let maskBuffer: Buffer | null = null;
  let maskSource: "vision" | "fallback" | "none" = "none";
  if (input.useMask !== false) {
    const bbox = await detectProductBox(sourceBuffer);
    if (bbox) {
      maskBuffer = await buildPreservationMask(outW, outH, bbox, 8);
      maskSource = "vision";
    } else {
      // Centered fallback — assume product occupies central 65% of frame.
      const fallbackW = Math.round(outW * 0.65);
      const fallbackH = Math.round(outH * 0.65);
      const fallbackBox = {
        x: Math.round((outW - fallbackW) / 2),
        y: Math.round((outH - fallbackH) / 2),
        width: fallbackW,
        height: fallbackH,
      };
      maskBuffer = await buildPreservationMask(outW, outH, fallbackBox, 2);
      maskSource = "fallback";
      console.log(
        `[touchup] vision bbox missing — using centered fallback mask (65% of frame)`,
      );
    }
  }

  const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });
  const sourceFile = await toFile(sourceBuffer, "source.png", { type: "image/png" });
  const editArgs: Parameters<typeof openai.images.edit>[0] = {
    model: "gpt-image-1",
    image: sourceFile,
    prompt: input.scenePrompt,
    size: input.outputSize,
    quality: input.quality,
    n: 1,
  };
  if (maskBuffer) {
    const maskFile = await toFile(maskBuffer, "mask.png", { type: "image/png" });
    editArgs.mask = maskFile;
  }

  // Narrow result type — `edit` overload returns ImagesResponse | Stream
  // depending on options. We never pass stream:true so cast accordingly.
  const res2 = (await openai.images.edit(editArgs)) as {
    data?: Array<{ b64_json?: string }>;
  };
  const b64 = res2.data?.[0]?.b64_json;
  if (!b64) {
    return null;
  }
  let finalBuffer: Buffer = Buffer.from(b64, "base64") as Buffer;

  // Optional logo composite on top
  if (input.logoBuffer) {
    try {
      finalBuffer = (await compositeLogoOnImage(
        finalBuffer,
        { buffer: input.logoBuffer },
        input.logoOpts ?? {
          position: "bottom-right",
          size_pct: 11,
          padding_pct: 3.5,
          with_backdrop: true,
          opacity: 1,
        },
      )) as Buffer;
    } catch (e) {
      console.warn(
        "[touchup] logo composite failed:",
        e instanceof Error ? e.message : e,
      );
    }
  }

  return { buffer: finalBuffer, used_mask: maskSource !== "none", mask_source: maskSource };
}

/**
 * Pick a product photo for a frame — rotates through available product
 * assets so different frames in a carousel use different source angles.
 */
export function pickSourceForFrame(
  productPhotos: Array<{ image_url: string }>,
  frameIndex: number,
): string | null {
  if (productPhotos.length === 0) return null;
  return productPhotos[frameIndex % productPhotos.length].image_url;
}

export type TouchupSettings = Pick<
  ImageGenSettings,
  "quality" | "logo_position" | "logo_size_pct" | "logo_padding_pct" | "logo_opacity" | "logo_with_backdrop"
>;
