"use client";

import { useLocale, useTranslations } from "next-intl";
import { usePathname, useRouter } from "@/i18n/navigation";
import { useTransition } from "react";

/**
 * Routes where the analysis content (rationale, narrative, action plans)
 * is generated by an LLM at sim creation time and locked to the locale
 * used at that moment. Toggling the URL locale on these routes only
 * translates the UI chrome — the body text stays in the original
 * language, which reads as a bug. We disable the switcher with a
 * tooltip explaining why instead of letting the toggle "lie".
 */
const LOCKED_ROUTE_PATTERN =
  /^\/(projects\/[^/]+\/results|share\/ensemble\/[^/]+)/;

export function LocaleSwitcher() {
  const t = useTranslations("common");
  const locale = useLocale();
  const router = useRouter();
  const pathname = usePathname();
  const [isPending, startTransition] = useTransition();

  const isLocked = LOCKED_ROUTE_PATTERN.test(pathname);
  const lockTooltip =
    locale === "ko"
      ? "결과 페이지는 분석 생성 시 언어로 고정됩니다 (LLM 생성 텍스트는 다시 번역되지 않습니다)."
      : "Results pages are locked to the language the analysis was generated in (LLM-written text is not re-translated).";

  return (
    <select
      aria-label={t("language")}
      title={isLocked ? lockTooltip : undefined}
      className="text-xs rounded-md border border-slate-200 bg-white px-2 py-1 text-slate-700 disabled:opacity-60 disabled:cursor-not-allowed"
      value={locale}
      disabled={isPending || isLocked}
      onChange={(e) => {
        const next = e.target.value as "ko" | "en";
        startTransition(() => {
          router.replace(pathname, { locale: next });
        });
      }}
    >
      <option value="ko">{t("korean")}</option>
      <option value="en">{t("english")}</option>
    </select>
  );
}
