/**
 * Renders a CountryReferenceBundle into a SQL seed file matching the format of
 * supabase/seeds/0001_kr_reference_data.sql.
 *
 * We write fetched data BACK as SQL seed files (rather than upserting directly)
 * so each annual refresh shows up as a reviewable git diff before going live.
 */
import type { CountryReferenceBundle, ProfessionIncomeRow } from "./types";

function jsonbLiteral(obj: unknown): string {
  return `'${JSON.stringify(obj).replace(/'/g, "''")}'::jsonb`;
}

function strLiteral(s: string): string {
  return `'${s.replace(/'/g, "''")}'`;
}

function formatIncomeRow(p: ProfessionIncomeRow): string {
  return `  (${strLiteral(p.professionCanonical)},
   ${jsonbLiteral(p.professionLocalized)},
   ${strLiteral(p.lifeStage)}, ${strLiteral(p.ageGroup)},
   ${p.incomeP25}::numeric, ${p.incomeMedian}::numeric, ${p.incomeP75}::numeric,
   ${strLiteral(p.displayBand.ko)},
   ${strLiteral(p.displayBand.en)})`;
}

export function renderSeed(bundle: CountryReferenceBundle): string {
  const { stats } = bundle;
  const fetchedAt = new Date().toISOString();

  const header = `-- ${stats.countryCode} reference data — auto-generated by scripts/fetch-reference/${stats.countryCode.toLowerCase()}.ts
-- Last refreshed: ${fetchedAt}
-- Source: ${stats.source}
--
-- Re-run safely: ON CONFLICT DO UPDATE makes this idempotent.`;

  const statsSql = `
insert into public.country_stats
  (country_code, data_year, country_name_en, country_name_local, currency,
   population, median_household_income, gdp_per_capita_usd,
   source, source_url)
values
  (${strLiteral(stats.countryCode)}, ${stats.dataYear},
   ${strLiteral(stats.countryNameEn)}, ${strLiteral(stats.countryNameLocal)},
   ${strLiteral(stats.currency)},
   ${stats.population}, ${stats.medianHouseholdIncome}, ${stats.gdpPerCapitaUsd},
   ${strLiteral(stats.source)}, ${strLiteral(stats.sourceUrl)})
on conflict (country_code, data_year) do update set
  country_name_en = excluded.country_name_en,
  country_name_local = excluded.country_name_local,
  currency = excluded.currency,
  population = excluded.population,
  median_household_income = excluded.median_household_income,
  gdp_per_capita_usd = excluded.gdp_per_capita_usd,
  source = excluded.source,
  source_url = excluded.source_url,
  fetched_at = now();`;

  const incomeRows = bundle.professions.map(formatIncomeRow).join(",\n");
  const incomeSql = `
with rows(profession_canonical, profession_localized, life_stage, age_group,
          p25, median, p75, display_ko, display_en) as (values
${incomeRows}
)
insert into public.country_profession_income
  (country_code, data_year, profession_canonical, profession_localized,
   life_stage, age_group, income_p25, income_median, income_p75,
   income_period, currency, display_band, source)
select ${strLiteral(stats.countryCode)}, ${stats.dataYear}, profession_canonical, profession_localized,
       life_stage, age_group, p25, median, p75,
       'annual', ${strLiteral(stats.currency)},
       jsonb_build_object('ko', display_ko, 'en', display_en),
       ${strLiteral(bundle.professionIncomeSource)}
from rows
on conflict (country_code, profession_canonical, age_group, data_year, life_stage)
  do update set
    income_p25 = excluded.income_p25,
    income_median = excluded.income_median,
    income_p75 = excluded.income_p75,
    display_band = excluded.display_band,
    profession_localized = excluded.profession_localized;`;

  const normRows = bundle.norms
    .map(
      (n) => `  (${strLiteral(stats.countryCode)}, ${stats.dataYear}, ${strLiteral(n.category)},
   ${jsonbLiteral(n.trustFactors)},
   ${jsonbLiteral(n.commonObjections)},
   ${jsonbLiteral(n.preferredChannels)},
   ${strLiteral(n.culturalNotes)},
   ${strLiteral(n.source)})`,
    )
    .join(",\n");

  const normsSql = `
insert into public.country_consumer_norms
  (country_code, data_year, category, trust_factors, common_objections,
   preferred_channels, cultural_notes, source)
values
${normRows}
on conflict (country_code, category, data_year) do update set
  trust_factors = excluded.trust_factors,
  common_objections = excluded.common_objections,
  preferred_channels = excluded.preferred_channels,
  cultural_notes = excluded.cultural_notes,
  source = excluded.source;`;

  return [header, statsSql, incomeSql, normsSql].join("\n") + "\n";
}
