-- Mr. AI — external integrations + synced signals (W4 sprint).
--
-- mrai_integrations: per-workspace OAuth connection state. One row per
--   (workspace_id, provider) — UNIQUE so reconnecting overwrites cleanly.
--   Tokens stored plaintext for v0 (internal dogfood). Production hardening
--   move: Supabase Vault or pgcrypto-encrypted columns + RLS-blocked select.
--
-- mrai_signals: normalized rollup the briefing/chat layer reads. Each row
--   is a workspace-scoped summary derived from a sync run — e.g.
--   "3 deals moved to Closed Won this week totaling $42K". The briefing
--   prompt pulls these via valid_until > now() so stale data drops out
--   automatically.
--
-- Why a normalized signals table instead of letting the briefing query
-- HubSpot live every morning? Latency + reliability + cost. Briefing
-- generation already takes 5-10s; adding 3 third-party API calls each
-- with their own failure modes triples failure surface. Sync is async
-- and cached.

create table if not exists public.mrai_integrations (
  id              uuid primary key default gen_random_uuid(),
  workspace_id    uuid not null references public.workspaces(id) on delete cascade,
  provider        text not null check (provider in ('hubspot', 'linkedin')),
  -- OAuth tokens. expires_at is for the access_token specifically;
  -- refresh_token is long-lived for hubspot.
  access_token    text not null,
  refresh_token   text,
  expires_at      timestamptz,
  scope           text,
  -- Provider-side account identifier (HubSpot portalId, etc) for diagnostics
  account_id      text,
  account_label   text,
  connected_by    uuid references auth.users(id) on delete set null,
  connected_at    timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create unique index if not exists mrai_integrations_ws_provider_uniq
  on public.mrai_integrations(workspace_id, provider);

create table if not exists public.mrai_signals (
  id              uuid primary key default gen_random_uuid(),
  workspace_id    uuid not null references public.workspaces(id) on delete cascade,
  source          text not null,        -- 'hubspot' | 'linkedin' | future ones
  source_id       text,                 -- provider-side identifier (deal id, post id, etc)
  -- Short human summary that goes straight into the briefing prompt.
  -- Generated by an LLM pass over the raw sync output.
  summary         text not null,
  -- Raw payload kept for audit / re-summarize / debugging
  raw             jsonb,
  valid_until     timestamptz,          -- null = no expiry, briefing uses anyway
  fetched_at      timestamptz not null default now()
);

create index if not exists mrai_signals_ws_source_idx
  on public.mrai_signals(workspace_id, source, fetched_at desc);

alter table public.mrai_integrations enable row level security;
alter table public.mrai_signals      enable row level security;

create policy "mrai_int_rw_members" on public.mrai_integrations
  for all using (public.is_workspace_member(workspace_id))
  with check (public.is_workspace_member(workspace_id));

create policy "mrai_sig_rw_members" on public.mrai_signals
  for all using (public.is_workspace_member(workspace_id))
  with check (public.is_workspace_member(workspace_id));
